name: thunderbird
version: "109.0b2-1"
summary: Mozilla Thunderbird email application
description: Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
confinement: strict
grade: stable
base: core20
compression: lzo

apps:
  thunderbird:
    command-chain: [ bin/gpg-shim, bin/tmpdir ]
    command: thunderbird.launcher
    extensions: [ gnome-3-38 ]
    environment:
      DISABLE_WAYLAND: 1
      HOME: "$SNAP_USER_COMMON"
      GTK_USE_PORTAL: 1
    plugs:
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - gpg-keys
      - home
      - network
      - network-control
      - opengl
      - audio-playback
      - removable-media
      - u2f-devices
    slots:
      - dbus-daemon

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  etc-thunderbird-policies:
    interface: system-files
    read: [/etc/thunderbird/policies]
  dot-thunderbird:
    interface: personal-files
    read: [$HOME/.thunderbird]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.mozilla.thunderbird

parts:
  thunderbird:
    plugin: nil
    override-pull: |
      VERSION=$(echo $SNAPCRAFT_PROJECT_VERSION | cut -d- -f1)
      BUILD=$(echo $SNAPCRAFT_PROJECT_VERSION | cut -d- -f2)
      URL=https://ftp.mozilla.org/pub/thunderbird/candidates/$VERSION-candidates/build$BUILD
      wget -O - $URL/linux-x86_64/en-US/thunderbird-$VERSION.tar.bz2 | tar -x -j --strip-components=1
    build-packages:
      - curl
      - wget
    stage-packages:
      - desktop-file-utils
      - gnupg # Needed to use Thunderbird >78 with smartcards.
      - gnupg-agent # Needed to use Thunderbird >78 with smartcards.
      - libblkid1
      - libgcrypt20
      - libgpg-error0
      - libgpgme11 # Needed to use Thunderbird >78 with smartcards.
      - liblzma5
      - libudev1
      - libuuid1
      - zlib1g
      - liblz4-1
      - libxt6
    organize:
      "snap/thunderbird/current/usr/*": usr/lib/thunderbird
    override-build: |
      VERSION=$(echo $SNAPCRAFT_PROJECT_VERSION | cut -d- -f1)
      BUILD=$(echo $SNAPCRAFT_PROJECT_VERSION | cut -d- -f2)
      XPIURL=https://ftp.mozilla.org/pub/thunderbird/candidates/$VERSION-candidates/build$BUILD/linux-x86_64/xpi
      snapcraftctl build
      set -eux
      cp -pr $SNAPCRAFT_PROJECT_DIR/distribution $SNAPCRAFT_PART_INSTALL
      mkdir $SNAPCRAFT_PART_INSTALL/distribution/extensions
      for locale in de es-ES fr it ja pt-PT pt-BR ru zh-CN; do curl -o "$SNAPCRAFT_PART_INSTALL/distribution/extensions/langpack-$locale@thunderbird.mozilla.org.xpi" "$XPIURL/$locale.xpi"; done
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -p $SNAPCRAFT_PROJECT_DIR/gpg-shim $SNAPCRAFT_PART_INSTALL/bin/
      cp -p $SNAPCRAFT_PROJECT_DIR/tmpdir $SNAPCRAFT_PART_INSTALL/bin/
      cp -pr $SNAPCRAFT_PART_SRC/* $SNAPCRAFT_PART_INSTALL
    prime: 
      - -usr/lib/*/libgio*
      - -usr/lib/*/libglib*
      - -usr/lib/*/libgm*

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [thunderbird]
    plugin: nil
    build-snaps: [core20, gnome-3-38-2004]
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

  launcher:
    plugin: nil
    override-prime: |
      cp "$SNAPCRAFT_PROJECT_DIR/thunderbird.launcher" "$SNAPCRAFT_PRIME/"
      cp "$SNAPCRAFT_PROJECT_DIR/patch-default-profile.py" "$SNAPCRAFT_PRIME/"
